export const PATIENT_TREATMENTS_REQUEST = 'PATIENT_TREATMENTS/REQUEST';
export const PATIENT_TREATMENTS_REQUEST_SUCCESS = 'PATIENT_TREATMENTS/REQUEST/SUCCESS';
export const PATIENT_TREATMENTS_REQUEST_ERROR = 'PATIENT_TREATMENTS/REQUEST/ERROR';
