export const PATIENT_BIOMARKERS_REQUEST = 'PATIENT_BIOMARKERS/REQUEST';
export const PATIENT_BIOMARKERS_REQUEST_SUCCESS = 'PATIENT_BIOMARKERS/REQUEST/SUCCESS';
export const PATIENT_BIOMARKERS_REQUEST_ERROR = 'PATIENT_BIOMARKERS/REQUEST/ERROR';
