export const PATIENT_QOL_REQUEST = 'PATIENT_QOL/REQUEST';
export const PATIENT_QOL_REQUEST_SUCCESS = 'PATIENT_QOL/REQUEST/SUCCESS';
export const PATIENT_QOL_REQUEST_ERROR = 'PATIENT_QOL/REQUEST/ERROR';
