export const PATIENT_TREATMENTS_REQUEST = 'PATIENT_TREATMENTS/REQUEST';
export const PATIENT_TREATMENTS_REQUEST_SUCCESS = 'PATIENT_TREATMENTS/REQUEST/SUCCESS';

export const PATIENT_TREATMENTS_REQUEST_FILTERS = 'PATIENT_TREATMENTS/REQUEST/SET_FILTERS';
