export const PATIENT_LIST_REQUEST = 'PATIENT_LIST/REQUEST';
export const PATIENT_LIST_REQUEST_SUCCESS = 'PATIENT_LIST/REQUEST/SUCCESS';
export const PATIENT_LIST_REQUEST_ERROR = 'PATIENT_LIST/REQUEST/ERROR';
