export const PATIENT_LIST_REQUEST = 'PATIENT_LIST/REQUEST';
export const PATIENT_LIST_REQUEST_SUCCESS = 'PATIENT_LIST/REQUEST/SUCCESS';
export const PATIENT_LIST_REQUEST_ERROR = 'PATIENT_LIST/REQUEST/ERROR';

export const PATIENT_PROFILE_REQUEST = 'PATIENT_PROFILE/REQUEST';
export const PATIENT_PROFILE_REQUEST_SUCCESS = 'PATIENT_PROFILE/REQUEST_SUCCESS';
export const PATIENT_PROFILE_REQUEST_ERROR = 'PATIENT_PROFILE/REQUEST_ERROR';

export const PATIENT_BIOMARKERS_REQUEST = 'PATIENT_BIOMARKERS/REQUEST';
export const PATIENT_BIOMARKERS_REQUEST_SUCCESS = 'PATIENT_BIOMARKERS/REQUEST/SUCCESS';
export const PATIENT_BIOMARKERS_REQUEST_ERROR = 'PATIENT_BIOMARKERS/REQUEST/ERROR';

export const PATIENT_TREATMENTS_REQUEST = 'PATIENT_TREATMENTS/REQUEST';
export const PATIENT_TREATMENTS_REQUEST_SUCCESS = 'PATIENT_TREATMENTS/REQUEST/SUCCESS';
export const PATIENT_TREATMENTS_REQUEST_ERROR = 'PATIENT_TREATMENTS/REQUEST/ERROR';

export const PATIENT_QOL_REQUEST = 'PATIENT_QOL/REQUEST';
export const PATIENT_QOL_REQUEST_SUCCESS = 'PATIENT_QOL/REQUEST/SUCCESS';
export const PATIENT_QOL_REQUEST_ERROR = 'PATIENT_QOL/REQUEST/ERROR';
