export const USER_LOGIN_REQUEST = 'USER_LOGIN/REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN/REQUEST/SUCCESS';
export const USER_LOGIN_REQUEST_ERROR = 'USER_LOGIN/REQUEST/ERROR';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT/REQUEST';
export const USER_LOGOUT_REQUEST_SUCCESS = 'USER_LOGOUT/REQUEST/SUCCESS';
export const USER_LOGOUT_REQUEST_ERROR = 'USER_LOGOUT/REQUEST/ERROR';
